[Appearance]
color_scheme_path=yourusername/.config/qt5ct/colors/colors_qt5-matugen.conf
custom_palette=true

[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x5\x5\0\0\0:\0\0\t\xf5\0\0\x5\x98\0\0\x5\x5\0\0\0:\0\0\t\xf5\0\0\x5\x98\0\0\0\0\0\0\0\0\n\0\0\0\x5\x5\0\0\0:\0\0\t\xf5\0\0\x5\x98)
