# BG/FG Colors
background            #18130b
foreground            #ece1d4
cursor                #f1be6d
selection_background  #55442a
selection_foreground  #f9dfbb

# Normal Colors
color0  #3a342b
color1  #ffb4ab
color2  #f1be6d
color3  #b6cea3
color4  #dcc3a1
color5  #7d570e
color6  #9b8f80
color7  #d2c4b4

# Bright Colors
color8  #4f4539
color9  #93000a
color10 #604100
color11 #384c2c
color12 #55442a
color13 #ece1d4
color14 #000000
color15 #ffdeae
