# BG/FG Colors
background            #101417
foreground            #e0e3e8
cursor                #96ccf8
selection_background  #384956
selection_foreground  #d3e5f6

# Normal Colors
color0  #313539
color1  #ffb4ab
color2  #96ccf8
color3  #cfc0e8
color4  #b7c9d9
color5  #28638a
color6  #8b9198
color7  #c1c7ce

# Bright Colors
color8  #41474d
color9  #93000a
color10 #004b70
color11 #4d4162
color12 #384956
color13 #e0e3e8
color14 #000000
color15 #cae6ff
