# BG/FG Colors
background            #1a1110
foreground            #f1dedc
cursor                #ffb4ab
selection_background  #5d3f3c
selection_foreground  #ffdad6

# Normal Colors
color0  #3d3231
color1  #ffb4ab
color2  #ffb4ab
color3  #e0c38c
color4  #e7bdb8
color5  #904a43
color6  #a08c8a
color7  #d8c2bf

# Bright Colors
color8  #534341
color9  #93000a
color10 #73332e
color11 #584419
color12 #5d3f3c
color13 #f1dedc
color14 #000000
color15 #ffdad6
