include colors/colors_kitty-matugen.conf

font_family JetBrains Mono Nerd Font
font_size 12.0

# Set the background opacity (0.0 is fully clear, 1.0 is solid)
background_opacity 0.80

# Keep the background slightly dark so white text remains readable
background #111111 

# Prevents the window from blinking or resetting transparency
dynamic_background_opacity yes

