-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
--

--TEST
--
--
-- Dynamic toggle bind between dwindle and scrolling layouts
--hl.bind(mainMod .. " + L", function()
--	-- Get the metadata object for your active workspace
--	local ws = hl.get_active_workspace()
--	if ws == nil then
--		return
--	end

-- Read the layout active on this workspace
--	if ws.tiled_layout == "dwindle" then
-- Force switch global layout to scrolling
--		hl.config({ general = { layout = "scrolling" } })
--	else
-- Force switch global layout back to dwindle
--		hl.config({ general = { layout = "dwindle" } })
--	end
--end, { description = "Toggle layout between dwindle and scrolling" }) --
